
name: Sample Workflow

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
jobs:
  sample-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Configurar credenciais da AWS
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
        -   name: Test s3
            run: |
                aws s3 ls
