description: |
    Este exemplo de ci simples

on:
  push:
    branches: [ main ]

jobs:

    security_checkov:
      runs-on: ubuntu-latest        
      steps:
        - uses: actions/checkout@v4
        - name: checkov
          run: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv venv
            uv pip install checkov
            uv run checkov -d .    
    security_dep_check:
      runs-on: ubuntu-latest        
      needs: [security_checkov]
      steps:
        - uses: actions/checkout@v4
        - name: pip-audit
          run: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv venv
            uv pip compile pyproject.toml -o requirements.txt
            uv pip install pip-audit
            uv run pip-audit -r requirements.txt 
    
    ci_artifact:
      runs-on: ubuntu-latest        
      needs: security_checkov
      steps:
        - uses: actions/checkout@v4
        - name: build
          run: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv venv
            uv build