description: |
    Este exemplo de ci simples

on:
  push:
    branches: [ main ]

jobs:
    check:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v4
        - name: build
          run: |
            ls -la        
        - name: checagem
          run: |
            echo "Fazendo a checagem ${{ vars.AWS_ACCESS_KEY }}"
            